# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from x_collector.v1 import x_collector_pb2 as x__collector_dot_v1_dot_x__collector__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in x_collector/v1/x_collector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XCollectorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectDailySearch = channel.unary_unary(
                '/social_monitor.x_collector.v1.XCollectorService/CollectDailySearch',
                request_serializer=x__collector_dot_v1_dot_x__collector__pb2.CollectDailySearchRequest.SerializeToString,
                response_deserializer=x__collector_dot_v1_dot_x__collector__pb2.CollectDailySearchResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/social_monitor.x_collector.v1.XCollectorService/CheckHealth',
                request_serializer=x__collector_dot_v1_dot_x__collector__pb2.CheckHealthRequest.SerializeToString,
                response_deserializer=x__collector_dot_v1_dot_x__collector__pb2.CheckHealthResponse.FromString,
                _registered_method=True)


class XCollectorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CollectDailySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XCollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectDailySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectDailySearch,
                    request_deserializer=x__collector_dot_v1_dot_x__collector__pb2.CollectDailySearchRequest.FromString,
                    response_serializer=x__collector_dot_v1_dot_x__collector__pb2.CollectDailySearchResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=x__collector_dot_v1_dot_x__collector__pb2.CheckHealthRequest.FromString,
                    response_serializer=x__collector_dot_v1_dot_x__collector__pb2.CheckHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'social_monitor.x_collector.v1.XCollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('social_monitor.x_collector.v1.XCollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XCollectorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectDailySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social_monitor.x_collector.v1.XCollectorService/CollectDailySearch',
            x__collector_dot_v1_dot_x__collector__pb2.CollectDailySearchRequest.SerializeToString,
            x__collector_dot_v1_dot_x__collector__pb2.CollectDailySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/social_monitor.x_collector.v1.XCollectorService/CheckHealth',
            x__collector_dot_v1_dot_x__collector__pb2.CheckHealthRequest.SerializeToString,
            x__collector_dot_v1_dot_x__collector__pb2.CheckHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
