// Reddit multi-pass daily scan configuration for the AI developer preset.
const redditSearchAllowedSubreddits = [
  "ArtificialInteligence",
  "OpenAI",
  "ClaudeAI",
  "ClaudeCode",
  "codex",
  "LocalLLaMA",
  "MachineLearning",
  "cybersecurity",
  "dartlang",
  "FlutterDev",
  "javascript",
  "node",
  "Python",
  "webdev",
  "programming",
  "technology",
  "artificial",
  "ChatGPT",
  "singularity",
  "typescript",
  "rust",
  "golang",
  "netsec",
  "CursorAI",
  "MCPservers",
  "AI_Agents",
  "LangChain",
  "OpenSourceAI",
  "vibecoding",
  "reactjs",
  "SaaS",
] as const;

const redditFreshListingSubreddits = [
  "ArtificialInteligence",
  "OpenAI",
  "ClaudeAI",
  "ClaudeCode",
  "codex",
  "LocalLLaMA",
  "MachineLearning",
  "cybersecurity",
  "programming",
  "webdev",
  "CursorAI",
  "MCPservers",
] as const;

const redditFreshListingPasses = redditFreshListingSubreddits.map(
  (subreddit) =>
    ({
      mode: "listing",
      subreddit,
      listing: "new",
      maxItems: 8,
      minScore: 0,
      includeComments: true,
      maxCommentsPerPost: 2,
    }) as const,
);

const redditPrimarySearchQuery =
  '"Claude Code" OR "OpenAI Codex" OR "AI agents" OR Anthropic OR LocalLLaMA OR LLM OR MCP';

export const redditDailyMultiPassConfig = {
  maxItems: 100,
  adaptivePagination: {
    enabled: true,
    targetItems: 150,
    maxPages: 4,
    minNewItemsPerPage: 2,
    maxDuplicateRate: 0.75,
  },
  sourceQueryPlanner: {
    enabled: true,
    rollout: "real_binding_canary",
    topic: redditPrimarySearchQuery,
    maxLanesPerSource: 8,
    maxItemsPerLane: 35,
    includeEnrichment: true,
  },
  scanPasses: [
    ...redditFreshListingPasses,
    {
      mode: "listing",
      subreddit: "ArtificialInteligence",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "OpenAI",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "ClaudeAI",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "ClaudeCode",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "codex",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "LocalLLaMA",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "MachineLearning",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "cybersecurity",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "dartlang",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "FlutterDev",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "javascript",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "node",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "Python",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "webdev",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "programming",
      listing: "top",
      topTime: "day",
      maxItems: 12,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "technology",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 15,
    },
    {
      mode: "listing",
      subreddit: "artificial",
      listing: "top",
      topTime: "day",
      maxItems: 10,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "ChatGPT",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 5,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "singularity",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 5,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "typescript",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 10,
    },
    {
      mode: "listing",
      subreddit: "rust",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "golang",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
    },
    {
      mode: "listing",
      subreddit: "netsec",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 5,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "CursorAI",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "MCPservers",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "AI_Agents",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "LangChain",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "OpenSourceAI",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "vibecoding",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 1,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
    {
      mode: "listing",
      subreddit: "reactjs",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 10,
    },
    {
      mode: "listing",
      subreddit: "SaaS",
      listing: "top",
      topTime: "day",
      maxItems: 8,
      minScore: 10,
    },
    {
      mode: "search",
      query: redditPrimarySearchQuery,
      maxItems: 10,
      minScore: 5,
      allowedSubreddits: redditSearchAllowedSubreddits,
      includeComments: true,
      maxCommentsPerPost: 3,
    },
  ],
} as const;
