// X/Twitter experimental daily scan configuration for the AI developer preset.
export const xTwitterDailyConfig = {
  language: "en",
  windowHours: 24,
  searchProducts: ["top", "latest"],
  maxItems: 100,
  limitPerProduct: 50,
  minLikes: 1,
  minRetweets: 0,
  minReplies: 0,
  adaptivePagination: {
    enabled: true,
    targetItems: 250,
    maxPages: 4,
    minNewItemsPerPage: 5,
    maxDuplicateRate: 0.75,
  },
  sourceQueryPlanner: {
    enabled: true,
    rollout: "real_binding_canary",
    maxLanesPerSource: 10,
    maxItemsPerLane: 50,
    includeEnrichment: false,
    maxSearchQueries: 10,
  },
  searchQueries: [
    '"Claude Code" OR "OpenAI Codex" OR Cursor OR "Cursor AI" OR "AI coding" OR "coding agent"',
    'MCP OR "MCP server" OR "model context protocol" OR "AI agent"',
    'OpenAI OR Anthropic OR Claude OR Gemini OR "AI model" OR LLM',
    'Flutter OR Dart OR TypeScript OR JavaScript OR "Node.js" OR Python OR Rust OR Go',
    'cybersecurity OR "AI security" OR "security vulnerability" OR infosec',
    'LangChain OR RAG OR "open source AI" OR "open source LLM" OR Ollama',
    '"vibe coding" OR "developer tools" OR "agentic coding" OR "AI infrastructure"',
    '"AI regulation" OR "AI governance" OR "AI safety" OR "AI privacy" OR "AI copyright"',
    'GPU OR inference OR "AI chips" OR "data center" OR "model training" OR benchmark',
  ],
} as const;
