// X/Twitter experimental daily scan configuration for the AI developer preset.
export const xTwitterDailyConfig = {
  language: "en",
  windowHours: 24,
  searchProducts: ["top", "latest"],
  maxItems: 100,
  limitPerProduct: 50,
  minLikes: 30,
  minRetweets: 0,
  minReplies: 0,
  requireQueryMatch: true,
  adaptivePagination: {
    enabled: true,
    targetItems: 250,
    maxPages: 4,
    minNewItemsPerPage: 5,
    maxDuplicateRate: 0.75,
  },
  sourceQueryPlanner: {
    enabled: true,
    rollout: "real_binding_canary",
    maxLanesPerSource: 10,
    maxItemsPerLane: 50,
    includeEnrichment: false,
    maxSearchQueries: 10,
  },
  searchQueries: [
    '"Claude Code" (release OR update OR workflow OR benchmark OR production OR GitHub OR skill OR MCP)',
    '("OpenAI Codex" OR "Cursor AI" OR "Cursor editor") (release OR update OR workflow OR benchmark OR production)',
    '(MCP OR "model context protocol") (server OR release OR integration OR security OR tool)',
    '(OpenAI OR Anthropic OR Claude OR Gemini) (release OR model OR API OR benchmark OR research)',
    '("AI agent" OR "coding agent") (release OR framework OR "open source" OR benchmark OR production)',
    '(cybersecurity OR "AI security" OR infosec) (vulnerability OR research OR release OR benchmark OR tool)',
    '(LangChain OR Ollama OR "RAG pipeline" OR "RAG system") (release OR benchmark OR production OR "open source")',
    '("vibe coding" OR "agentic coding") (tool OR workflow OR release OR benchmark OR production)',
    '"AI regulation" OR "AI governance" OR "AI safety" OR "AI privacy" OR "AI copyright"',
    '"LLM inference" OR "AI chips" OR "AI data center" OR "model training" OR "AI benchmark" OR "LLM benchmark"',
  ],
} as const;
