import type { SourceReadinessProfile } from '../../ports';

export const sourceReadinessProfiles: readonly SourceReadinessProfile[] = [
  {
    providerKey: 'fake-source',
    state: 'enabled_beta',
    acquisitionMode: 'deterministic_local_adapter',
    approvalOwner: 'engineering',
    termsNotes: 'Local fake provider for MVP certification only.',
    credentialOwnership: 'none',
    quotaModel: 'none',
    retentionNotes: 'Synthetic data only.',
    cursorModel: 'opaque',
    identityStrategy: ['externalId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'link'],
    unsupportedContentUnits: ['comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'zero',
    betaEnablementCriteria: ['Certification tests pass', 'No external network dependency'],
    rollbackPlan: 'Disable fake provider registration.',
  },
  {
    providerKey: 'hacker-news',
    state: 'enabled_beta',
    acquisitionMode: 'official_or_open_api',
    approvalOwner: 'engineering',
    termsNotes: 'Uses public HN Firebase listings and HN Algolia search endpoints; no credentials required.',
    credentialOwnership: 'none',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public story/comment provenance; avoid raw payload retention by default.',
    cursorModel: 'time',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'media'],
    estimatedCostPerScan: 'low',
    betaEnablementCriteria: ['HN fixtures pass certification', 'Live HTTP adapter smoke passes', 'Rate-limit behavior documented'],
    rollbackPlan: 'Return source health unavailable and stop scheduling HN bindings.',
  },
  {
    providerKey: 'rss',
    state: 'enabled_beta',
    acquisitionMode: 'feed_polling_with_site_policy_respect',
    approvalOwner: 'engineering',
    termsNotes: 'Use RSS/Atom feeds with ETag/Last-Modified where available; no broad page scraping.',
    credentialOwnership: 'none',
    quotaModel: 'per_source_binding',
    retentionNotes: 'Respect publisher policy; raw payload retention disabled unless explicitly allowed.',
    cursorModel: 'etag_last_modified',
    identityStrategy: ['guid', 'canonicalUrl', 'contentHash'],
    supportedContentUnits: ['post', 'link'],
    unsupportedContentUnits: ['comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'low_to_medium',
    betaEnablementCriteria: [
      'RSS certification fixtures pass for malformed, duplicate and missing GUID items',
      'HTTP cache headers supported',
      'SSRF URL policy enforced',
    ],
    rollbackPlan: 'Pause affected feed bindings and expose source health degraded.',
  },
  {
    providerKey: 'github',
    state: 'enabled_beta',
    acquisitionMode: 'official_or_open_api',
    approvalOwner: 'engineering',
    termsNotes: 'Uses GitHub REST search API for public issues; no GitHub UI scraping.',
    credentialOwnership: 'none',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public issue provenance; avoid raw payload retention by default.',
    cursorModel: 'page_token',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'media'],
    estimatedCostPerScan: 'low_with_strict_rate_limits',
    betaEnablementCriteria: [
      'GitHub certification fixtures pass',
      'Official REST API path only',
      'Rate-limit behavior documented',
    ],
    rollbackPlan: 'Pause GitHub bindings and expose source health rate_limited or degraded.',
  },
  {
    providerKey: 'reddit',
    state: 'enabled_beta',
    acquisitionMode: 'official_oauth_api',
    approvalOwner: 'product_and_legal',
    termsNotes: 'Uses Reddit OAuth API only; no unsafe scraping or bypassing platform controls.',
    credentialOwnership: 'tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Store normalized public post provenance; raw payload retention disabled unless explicitly approved.',
    cursorModel: 'opaque',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'community', 'link'],
    unsupportedContentUnits: ['profile', 'media'],
    estimatedCostPerScan: 'low_to_medium_depending_on_reddit_quota',
    betaEnablementCriteria: [
      'Reddit OAuth credential supplied by tenant',
      'Certification fixtures pass',
      'Backpressure and rate-limit metrics enabled',
    ],
    rollbackPlan: 'Pause Reddit bindings and expose source health auth_failed or rate_limited.',
  },
  {
    providerKey: 'x-twitter',
    state: 'provider_only',
    acquisitionMode: 'approved_paid_api_or_vendor',
    approvalOwner: 'product_and_legal',
    termsNotes: 'No production path without explicit policy, cost and access approval.',
    credentialOwnership: 'vendor_or_tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention constraints depend on approved provider contract.',
    cursorModel: 'since_id',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'profile', 'media', 'link'],
    unsupportedContentUnits: ['community'],
    estimatedCostPerScan: 'high_or_unknown',
    betaEnablementCriteria: ['Paid access approved', 'Quota budget enforced', 'Deletion policy implemented'],
    rollbackPlan: 'Do not enable direct adapter; use vendor-only integration if approved.',
  },
  {
    providerKey: 'telegram',
    state: 'manual_only',
    acquisitionMode: 'bot_or_channel_api_with_clear_scope',
    approvalOwner: 'product_and_legal',
    termsNotes: 'Only channels/scopes with explicit authorization.',
    credentialOwnership: 'tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention depends on channel/admin authorization and user policy.',
    cursorModel: 'opaque',
    identityStrategy: ['providerId', 'channelId', 'messageId'],
    supportedContentUnits: ['post', 'media', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'comment'],
    estimatedCostPerScan: 'unknown',
    betaEnablementCriteria: ['Authorized scope model', 'Credential lifecycle implemented'],
    rollbackPlan: 'Disable automation and keep manual import path only.',
  },
];
