import type { SourceReadinessProfile } from '../../ports';

export const sourceReadinessProfiles: readonly SourceReadinessProfile[] = [
  {
    providerKey: 'fake-source',
    state: 'enabled_beta',
    acquisitionMode: 'deterministic_local_adapter',
    approvalOwner: 'engineering',
    termsNotes: 'Local fake provider for MVP certification only.',
    credentialOwnership: 'none',
    quotaModel: 'none',
    retentionNotes: 'Synthetic data only.',
    cursorModel: 'opaque',
    identityStrategy: ['externalId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'link'],
    unsupportedContentUnits: ['comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'zero',
    betaEnablementCriteria: ['Certification tests pass', 'No external network dependency'],
    rollbackPlan: 'Disable fake provider registration.',
  },
  {
    providerKey: 'hacker-news',
    state: 'enabled_beta',
    acquisitionMode: 'official_or_open_api',
    approvalOwner: 'engineering',
    termsNotes: 'Uses public HN Firebase listings and HN Algolia search endpoints; no credentials required.',
    credentialOwnership: 'none',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public story/comment provenance; avoid raw payload retention by default.',
    cursorModel: 'time',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'media'],
    estimatedCostPerScan: 'low',
    betaEnablementCriteria: ['HN fixtures pass certification', 'Live HTTP adapter smoke passes', 'Rate-limit behavior documented'],
    rollbackPlan: 'Return source health unavailable and stop scheduling HN bindings.',
  },
  {
    providerKey: 'rss',
    state: 'profiled',
    acquisitionMode: 'feed_polling_with_site_policy_respect',
    approvalOwner: 'engineering',
    termsNotes: 'Use RSS/Atom feeds with ETag/Last-Modified where available; no broad page scraping.',
    credentialOwnership: 'none',
    quotaModel: 'per_source_binding',
    retentionNotes: 'Respect publisher policy; raw payload retention disabled unless explicitly allowed.',
    cursorModel: 'etag_last_modified',
    identityStrategy: ['guid', 'canonicalUrl', 'contentHash'],
    supportedContentUnits: ['post', 'link'],
    unsupportedContentUnits: ['comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'low_to_medium',
    betaEnablementCriteria: ['RSS malformed/duplicate fixtures pass', 'HTTP cache headers supported'],
    rollbackPlan: 'Pause affected feed bindings and expose source health degraded.',
  },
  {
    providerKey: 'reddit',
    state: 'profiled',
    acquisitionMode: 'official_api_or_approved_vendor',
    approvalOwner: 'product_and_legal',
    termsNotes: 'No unsafe scraping or bypassing platform controls.',
    credentialOwnership: 'tenant_or_vendor',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention and commercial monitoring constraints require approval before enablement.',
    cursorModel: 'opaque',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'community', 'link'],
    unsupportedContentUnits: ['profile', 'media'],
    estimatedCostPerScan: 'unknown_until_access_path_approved',
    betaEnablementCriteria: ['Approved access path', 'Cost model accepted', 'Certification fixtures available'],
    rollbackPlan: 'Keep provider disabled and show readiness-profile only.',
  },
  {
    providerKey: 'x-twitter',
    state: 'provider_only',
    acquisitionMode: 'approved_paid_api_or_vendor',
    approvalOwner: 'product_and_legal',
    termsNotes: 'No production path without explicit policy, cost and access approval.',
    credentialOwnership: 'vendor_or_tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention constraints depend on approved provider contract.',
    cursorModel: 'since_id',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'profile', 'media', 'link'],
    unsupportedContentUnits: ['community'],
    estimatedCostPerScan: 'high_or_unknown',
    betaEnablementCriteria: ['Paid access approved', 'Quota budget enforced', 'Deletion policy implemented'],
    rollbackPlan: 'Do not enable direct adapter; use vendor-only integration if approved.',
  },
  {
    providerKey: 'telegram',
    state: 'manual_only',
    acquisitionMode: 'bot_or_channel_api_with_clear_scope',
    approvalOwner: 'product_and_legal',
    termsNotes: 'Only channels/scopes with explicit authorization.',
    credentialOwnership: 'tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention depends on channel/admin authorization and user policy.',
    cursorModel: 'opaque',
    identityStrategy: ['providerId', 'channelId', 'messageId'],
    supportedContentUnits: ['post', 'media', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'comment'],
    estimatedCostPerScan: 'unknown',
    betaEnablementCriteria: ['Authorized scope model', 'Credential lifecycle implemented'],
    rollbackPlan: 'Disable automation and keep manual import path only.',
  },
];
