import type { SourceReadinessProfile } from '../../ports';

export const sourceReadinessProfiles: readonly SourceReadinessProfile[] = [
  {
    providerKey: 'fake-source',
    state: 'certification_ready',
    runtimeReadiness: 'fixture_ready',
    liveBetaBlockers: ['Synthetic provider is not a real external source.'],
    acquisitionMode: 'deterministic_local_adapter',
    approvalOwner: 'engineering',
    termsNotes: 'Local fake provider for MVP certification only.',
    credentialOwnership: 'none',
    quotaModel: 'none',
    retentionNotes: 'Synthetic data only.',
    cursorModel: 'opaque',
    identityStrategy: ['externalId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'link'],
    unsupportedContentUnits: ['comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'zero',
    betaEnablementCriteria: ['Certification tests pass', 'No external network dependency'],
    rollbackPlan: 'Disable fake provider registration.',
  },
  {
    providerKey: 'hacker-news',
    state: 'enabled_beta',
    runtimeReadiness: 'fixture_ready',
    liveBetaBlockers: ['Live HTTP smoke and deployed rate-limit evidence required before external beta.'],
    acquisitionMode: 'official_or_open_api',
    approvalOwner: 'engineering',
    termsNotes: 'Uses public HN Firebase listings and HN Algolia search endpoints; no credentials required.',
    credentialOwnership: 'none',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public story/comment provenance; avoid raw payload retention by default.',
    cursorModel: 'time',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'media'],
    estimatedCostPerScan: 'low',
    betaEnablementCriteria: ['HN fixtures pass certification', 'Live HTTP adapter smoke passes', 'Rate-limit behavior documented'],
    rollbackPlan: 'Return source health unavailable and stop scheduling HN bindings.',
  },
  {
    providerKey: 'rss',
    state: 'enabled_beta',
    runtimeReadiness: 'fixture_ready',
    liveBetaBlockers: ['Representative live feed allowlist, HTTP cache and SSRF controls need deployed evidence.'],
    acquisitionMode: 'feed_polling_with_site_policy_respect',
    approvalOwner: 'engineering',
    termsNotes: 'Use RSS/Atom feeds with ETag/Last-Modified where available; no broad page scraping.',
    credentialOwnership: 'none',
    quotaModel: 'per_source_binding',
    retentionNotes: 'Respect publisher policy; raw payload retention disabled unless explicitly allowed.',
    cursorModel: 'etag_last_modified',
    identityStrategy: ['guid', 'canonicalUrl', 'contentHash'],
    supportedContentUnits: ['post', 'link'],
    unsupportedContentUnits: ['comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'low_to_medium',
    betaEnablementCriteria: [
      'RSS certification fixtures pass for malformed, duplicate and missing GUID items',
      'HTTP cache headers supported',
      'SSRF URL policy enforced',
    ],
    rollbackPlan: 'Pause affected feed bindings and expose source health degraded.',
  },
  {
    providerKey: 'github-issues',
    state: 'enabled_beta',
    runtimeReadiness: 'fixture_ready',
    liveBetaBlockers: ['Live GitHub issues API smoke and deployed rate-limit budget evidence required before external beta.'],
    acquisitionMode: 'official_or_open_api',
    approvalOwner: 'engineering',
    termsNotes: 'Uses GitHub REST search API for public issues; no GitHub UI scraping.',
    credentialOwnership: 'none',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public issue provenance; avoid raw payload retention by default.',
    cursorModel: 'page_token',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'media'],
    estimatedCostPerScan: 'low_with_strict_rate_limits',
    betaEnablementCriteria: [
      'GitHub issues certification fixtures pass',
      'Official REST API path only',
      'Rate-limit behavior documented',
    ],
    rollbackPlan: 'Pause GitHub issues bindings and expose source health rate_limited or degraded.',
  },
  {
    providerKey: 'github-repo-radar',
    state: 'enabled_beta',
    runtimeReadiness: 'fixture_ready',
    liveBetaBlockers: [
      'BigQuery GH Archive credentials/quota evidence, npm run check:github-repo-radar-live-smoke, npm run check:github-repo-radar-prisma-live-e2e and GitHub live verification rate-limit budget required before external beta.',
    ],
    acquisitionMode: 'official_or_open_api',
    approvalOwner: 'engineering',
    termsNotes: 'Uses GH Archive BigQuery public dataset and GitHub REST repository API; no GitHub UI scraping.',
    credentialOwnership: 'app',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public repository trend metadata and daily snapshots; raw BigQuery rows are not retained.',
    cursorModel: 'time',
    identityStrategy: ['repositoryFullName', 'canonicalUrl', 'checkedAt'],
    supportedContentUnits: ['link'],
    unsupportedContentUnits: ['post', 'comment', 'profile', 'community', 'media'],
    estimatedCostPerScan: 'medium_with_bigquery_cost_guard',
    betaEnablementCriteria: [
      'Fixture certification passes',
      'BigQuery maximumBytesBilled is configured',
      'GITHUB_REPO_RADAR_LIVE_SMOKE=1 npm run check:github-repo-radar-live-smoke passes in staging',
      'GITHUB_REPO_RADAR_PRISMA_LIVE_E2E=1 npm run check:github-repo-radar-prisma-live-e2e proves Postgres source/feed/trend persistence',
      'GitHub REST live verifier rate-limit behavior documented',
      'Trend history persistence smoke passes',
    ],
    rollbackPlan: 'Pause GitHub repo radar bindings and expose source health bigquery_unavailable or rate_limited.',
  },
  {
    providerKey: 'reddit',
    state: 'enabled_beta',
    runtimeReadiness: 'fixture_ready',
    liveBetaBlockers: ['App-only OAuth client credentials and live Reddit API rate-limit evidence required before external beta.'],
    acquisitionMode: 'official_oauth_api',
    approvalOwner: 'product_and_legal',
    termsNotes: 'Uses Reddit OAuth API only; no unsafe scraping or bypassing platform controls.',
    credentialOwnership: 'app_with_optional_tenant_override',
    quotaModel: 'per_app',
    retentionNotes: 'Store normalized public post provenance; raw payload retention disabled unless explicitly approved.',
    cursorModel: 'opaque',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'community', 'link'],
    unsupportedContentUnits: ['profile', 'media'],
    estimatedCostPerScan: 'low_to_medium_depending_on_reddit_quota',
    betaEnablementCriteria: [
      'Reddit app-only OAuth client credentials supplied through runtime secret boundary',
      'Optional tenant OAuth override remains encrypted and scoped',
      'Certification fixtures pass',
      'Backpressure and rate-limit metrics enabled',
    ],
    rollbackPlan: 'Pause Reddit bindings and expose source health auth_failed or rate_limited.',
  },
  {
    providerKey: 'x-twitter',
    state: 'provider_only',
    runtimeReadiness: 'deferred',
    liveBetaBlockers: [
      'Paid X API or approved vendor contract is required before enablement.',
      'Read-only scopes, endpoint rate limits, retention policy and spend cap must be proven before beta binding.',
    ],
    acquisitionMode: 'approved_paid_api_or_vendor',
    approvalOwner: 'product_and_legal',
    termsNotes: 'No production path without explicit policy, cost, retention, deletion and access approval.',
    credentialOwnership: 'vendor_or_tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention constraints depend on approved provider contract.',
    cursorModel: 'since_id',
    identityStrategy: ['providerId', 'canonicalUrl'],
    supportedContentUnits: ['post', 'comment', 'profile', 'media', 'link'],
    unsupportedContentUnits: ['community'],
    estimatedCostPerScan: 'high_or_endpoint_dependent',
    betaEnablementCriteria: [
      'Paid access or approved vendor path accepted',
      'Read-only scopes are limited to enabled endpoints',
      'Quota budget and spend cap are enforced',
      'Rate-limit headers are captured in live evidence',
      'Deletion and retention policy implemented',
    ],
    rollbackPlan: 'Do not enable direct adapter; use vendor-only integration if approved.',
  },
  {
    providerKey: 'telegram',
    state: 'manual_only',
    runtimeReadiness: 'deferred',
    liveBetaBlockers: ['Authorized channel scope and credential lifecycle are required before automation.'],
    acquisitionMode: 'bot_or_channel_api_with_clear_scope',
    approvalOwner: 'product_and_legal',
    termsNotes: 'Only channels/scopes with explicit authorization.',
    credentialOwnership: 'tenant',
    quotaModel: 'per_credential',
    retentionNotes: 'Retention depends on channel/admin authorization and user policy.',
    cursorModel: 'opaque',
    identityStrategy: ['providerId', 'channelId', 'messageId'],
    supportedContentUnits: ['post', 'media', 'link'],
    unsupportedContentUnits: ['profile', 'community', 'comment'],
    estimatedCostPerScan: 'unknown',
    betaEnablementCriteria: ['Authorized scope model', 'Credential lifecycle implemented'],
    rollbackPlan: 'Disable automation and keep manual import path only.',
  },
];
