import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const jsonFixturePath = "apps/frontend/features/summaries/test/fixtures/" +
  "reader_post_promotion_v3_sql_readback.json";
const dartFixturePath = "apps/frontend/features/summaries/test/support/" +
  "reader_post_promotion_v3_sql_readback_fixture.dart";
const writeFlag = "--write-reader-summary-v3-flutter-fixture";
const uuidPattern = /[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/giu;
const displayUuidPattern = /[0-9a-f]{8} [0-9a-f]{4} [1-8][0-9a-f]{3} [89ab][0-9a-f]{3} [0-9a-f]{12}/giu;

/** Normal CI asserts freshness. Regeneration is an explicit PostgreSQL
 * contract mode so a test run can never silently rewrite Flutter source. */
export const assertFlutterV3FixtureFresh = (
  sqlRestTransport: unknown,
  options: {
    readonly jsonFixturePath?: string;
    readonly dartFixturePath?: string;
    readonly write?: boolean;
  } = {},
): void => {
  const jsonBytes = `${JSON.stringify(canonicalizeSqlRestTransport(sqlRestTransport))}\n`;
  const dartBytes = dartFixtureSource(jsonBytes);
  const jsonPath = options.jsonFixturePath ?? jsonFixturePath;
  const dartPath = options.dartFixturePath ?? dartFixturePath;
  const write = options.write ?? process.argv.includes(writeFlag);
  if (write) {
    writeFileSync(jsonPath, jsonBytes, "utf8");
    writeFileSync(dartPath, dartBytes, "utf8");
    return;
  }
  if (readFileSync(jsonPath, "utf8") !== jsonBytes) {
    throw new Error(`Flutter V3 SQL readback fixture is stale; regenerate with npm run ` +
      `check:reader-summary-v3-postgres -- ${writeFlag}`);
  }
  if (readFileSync(dartPath, "utf8") !== dartBytes) {
    throw new Error(`Flutter V3 Dart support fixture is stale; regenerate with npm run ` +
      `check:reader-summary-v3-postgres -- ${writeFlag}`);
  }
};

const dartFixtureSource = (jsonBytes: string): string => {
  const encoded = Buffer.from(jsonBytes, "utf8").toString("base64");
  const chunks = encoded.match(/.{1,76}/gu) ?? [];
  const literals = chunks.map((chunk) => `    '${chunk}'`);
  const finalLiteral = literals.pop();
  if (finalLiteral === undefined) throw new Error("Flutter V3 fixture is empty");
  return [
    "// GENERATED CODE - DO NOT MODIFY BY HAND.",
    "// Generated by reader-summary-v3-postgres-flutter-fixture.ts.",
    "",
    "const String readerPostPromotionV3SqlReadbackJsonBase64 =",
    ...literals,
    `${finalLiteral};`,
    "",
  ].join("\n");
};

export const canonicalizeSqlRestTransport = (value: unknown): unknown => {
  const identifiers = new Map<string, string>();
  const replacement = (id: string): string => {
      const normalized = id.toLowerCase();
      const existing = identifiers.get(normalized);
      if (existing !== undefined) return existing;
      const suffix = String(identifiers.size + 1).padStart(12, "0");
      const canonical = `00000000-0000-4000-8000-${suffix}`;
      identifiers.set(normalized, canonical);
      return canonical;
  };
  const replaceIdentifiers = (text: string): string => text
    .replace(uuidPattern, replacement)
    .replace(displayUuidPattern, (id) =>
      replacement(id.replaceAll(" ", "-")).replaceAll("-", " "));
  const normalize = (input: unknown): unknown => {
    if (typeof input === "string") return replaceIdentifiers(input);
    if (Array.isArray(input)) return input.map(normalize);
    if (record(input)) return Object.fromEntries(Object.entries(input).map(
      ([key, child]) => [key, key === "canonicalPayload" ? child : normalize(child)],
    ));
    return input;
  };
  const transport = normalize(JSON.parse(JSON.stringify(value))) as Record<string, unknown>;
  const brief = requiredRecord(transport.readerBrief, "readerBrief");
  for (const lane of ["topReads", "selectedPosts"] as const) {
    const cards = brief[lane];
    if (cards === undefined) continue;
    if (!Array.isArray(cards)) throw new Error(`SQL REST ${lane} is not an array`);
    for (const cardValue of cards) {
      const card = requiredRecord(cardValue, `${lane} card`);
      const attestation = requiredRecord(card.promotionAttestation,
        `${lane} promotion attestation`);
      if (attestation.schemaVersion !== "reader_post_promotion_attestation.v3") continue;
      const originalCanonical = attestation.canonicalPayload;
      if (typeof originalCanonical !== "string") {
        throw new Error("SQL REST V3 canonical payload is missing");
      }
      const body = normalize(JSON.parse(originalCanonical)) as Record<string, unknown>;
      canonicalizeOpaqueDigests(body);
      const presentation = requiredRecord(body.presentation, "V3 presentation");
      const seal = requiredRecord(presentation.displayHeadline, "V3 display headline seal");
      card.displayHeadline = seal.headline;
      for (const [key, child] of Object.entries(body)) attestation[key] = child;
      const canonicalPayload = stableJson(body);
      attestation.canonicalPayload = canonicalPayload;
      attestation.digest = sha256(canonicalPayload);
    }
  }
  return transport;
};

const canonicalizeOpaqueDigests = (body: Record<string, unknown>): void => {
  const assessment = requiredRecord(body.assessment, "V3 assessment");
  assessment.sourceSnapshotSha256 = "1".repeat(64);
  assessment.inputSha256 = "2".repeat(64);
  const presentation = requiredRecord(body.presentation, "V3 presentation");
  presentation.presentationInputDigest = "4".repeat(64);
  const seal = requiredRecord(presentation.displayHeadline, "V3 display headline seal");
  const headline = requiredRecord(seal.headline, "V3 display headline");
  const binding = requiredRecord(headline.binding, "V3 display headline binding");
  binding.interestDigest = "a".repeat(64);
  binding.reviewedInputDigest = "b".repeat(64);
  presentation.presentationIdentity = sha256(stableJson({
    schemaVersion: "reader_post_presentation.v3",
    sourceSnapshotSha256: assessment.sourceSnapshotSha256,
    presentationInputDigest: presentation.presentationInputDigest,
    displayHeadline: seal,
  }));
};

const requiredRecord = (value: unknown, label: string): Record<string, unknown> => {
  if (!record(value)) throw new Error(`${label} is missing`);
  return value;
};
const record = (value: unknown): value is Record<string, unknown> =>
  value !== null && typeof value === "object" && !Array.isArray(value);
const sha256 = (value: string): string => createHash("sha256")
  .update(value, "utf8").digest("hex");
const stableJson = (value: unknown): string => JSON.stringify(sorted(value));
const sorted = (value: unknown): unknown => Array.isArray(value) ? value.map(sorted)
  : record(value) ? Object.fromEntries(Object.keys(value).sort().map((key) =>
    [key, sorted(value[key])])) : value;
