import { releaseEvidence } from "./story-release-event-identity.spec-support";

const left = releaseEvidence("Northstar introduces Juniper 2.8 for coding at lower cost\nNorthstar releases Juniper 2.8 on September 1. Juniper 2.8 has lower cost for coding workloads. The announcement describes the new model and its agentic tasks.");
const rightLead = "Northstar releases Juniper 2.8 on September 1. Juniper 2.8 improves coding workloads vs its predecessor. The announcement describes the new model and its agentic tasks.";
const example = (name: string, detail: string, mayMerge = false) => ({ name, mayMerge, inputs: [left,
  releaseEvidence(`Northstar launches Juniper 2.8 for coding compared to its predecessor\n${rightLead} ${detail}`, "right", "x-twitter"),
] });

/** Adjacent grammar, synthetic and deliberately independent of sealed eval data. */
export const primaryEventGrammarCases = [
  ...[
    example("suffixed version retains unsupported primary state", "Juniper 2.8 is stolen."),
    example("suffixed version retains descriptive primary state", "Juniper 2.8 is more efficient on coding tasks.", true),
  ].map((testCase) => ({ ...testCase, inputs: testCase.inputs.map((input) => ({ ...input,
    title: input.title.replaceAll("2.8", "2.8a"),
    bodyPreview: input.bodyPreview?.replaceAll("2.8", "2.8a"),
    sourceText: input.sourceText?.replaceAll("2.8", "2.8a"),
  })) })),
  ...["Maple 4.6 is available", "Juniper 2.8 improves coding", "Northstar measured the model"]
    .flatMap((assertion) => ["after", "because", "when", "since", "as"].map((join) => example(
      `subordinate action remains independent: ${assertion} ${join}`,
      `${assertion} ${join} intruders stole customer records.`,
    ))),
  example("causal clause describes the same release property",
    "Juniper 2.8 improves coding throughput because it uses fewer resources.", true),
  ...["is under attack", "has a credential leak", "is stolen", "remains inaccessible"].map((predicate) =>
    example(`unsupported explicit primary state: ${predicate}`, `Juniper 2.8 ${predicate}.`)),
  example("comparative primary state", "Juniper 2.8 is more efficient on coding tasks.", true),
  ...[",", " and"].map((boundary) => example(`unfamiliar plural predicate after measurement${boundary}`,
    `Northstar measured the model${boundary} intruders siphon secrets.`)),
  example("unfamiliar named predicate after release",
    "Juniper 2.8 is available, Cedar Labs probe an intrusion."),
  example("branded product appositive is not a separate actor",
    "Northstar releases Cedar Iris 4.6. Cedar Iris 4.6, our model for researchers and developers, is available today. Juniper 2.8 is available today.", true),
  ...[
    "Maple 4.6 is available",
    "Juniper 2.8 was released on September 1",
    "Northstar measured the model",
    "Cedar releases Maple 4.6 on September 1",
  ].flatMap((assertion) => [",", " although"].map((boundary) => example(
    `explicit action after supported clause: ${assertion}${boundary}`,
    `${assertion}${boundary} intruders stole customer records.`,
  ))),
  example("comma separates matching explicit release facts",
    "Maple 4.6 is available, Juniper 2.8 was released on September 1.", true),
  example("subordinate clause retains matching primary stage",
    "Maple 4.6 is in preview although Juniper 2.8 is generally available.", true),
  ...["while", "whereas", "but", "and"].map((join) => example(`two subjects joined by ${join}`,
    `Maple 4.6 is generally available, ${join} Juniper 2.8 is still in beta preview.`)),
  example("two subjects separated by semicolon", "Maple 4.6 is generally available; Juniper 2.8 is still in beta preview."),
  example("two subjects separated by comma", "Maple 4.6 is generally available, Juniper 2.8 is still in beta preview."),
  example("unparsed mixed subject clause", "Maple 4.6 is generally available although Juniper 2.8 remains in beta preview."),
  example("other subject followed by lowercase actor", "Maple 4.6 is generally available and intruders stole customer records."),
  example("other subject followed by active primary date", "Northstar releases Maple 4.6 on September 1, while Northstar releases Juniper 2.8 on August 1."),
  example("conflicting actor repeats primary release", "Cedar releases Juniper 2.8 on September 1."),
  example("same actor repeats primary release", "Northstar releases Juniper 2.8 on September 1.", true),
  example("conflicting passive release actor", "Juniper 2.8 was released by Cedar on September 1."),
  example("same passive release actor", "Juniper 2.8 was released by Northstar on September 1.", true),
  example("ambiguous pronoun after other subject", "Maple 4.6 is generally available, while it is still in preview."),
  example("primary date after other subject", "Maple 4.6 was released on August 1, while Juniper 2.8 was released on September 1.", true),
  example("primary stage after other subject", "Maple 4.6 is in preview, while Juniper 2.8 is generally available.", true),
  example("independent quantified workload", "Cedar Labs executed 275 programming tasks on Juniper 2.8 and found a regression."),
  example("independent alternate experimental object", "Cedar Labs completed 42 reasoning trials on Juniper 2.8."),
  example("independent passive quantified workload", "275 programming tasks were executed by Cedar on Juniper 2.8."),
  example("unknown named actor action", "Cedar Labs audited Juniper 2.8 after the launch."),
  example("lowercase named actor action", "cedar labs audited Juniper 2.8 after the launch."),
  example("publisher quotes a different event", "Northstar says intruders stole customer records."),
  example("unknown publisher present predicate", "Northstar suspends access for existing Juniper 2.8 customers."),
  example("publisher is not enough for unrelated action", "Northstar suspended access for existing Juniper 2.8 customers."),
  example("active later event", "Intruders compromised the coding service and obtained customer records."),
  example("unfamiliar plural actor predicate", "Intruders siphon customer records from the coding service."),
  example("lowercase plural actor predicate", "intruders siphon customer records from the coding service."),
  example("determined plural actor predicate", "The intruders siphon customer records from the coding service."),
  example("passive later event", "Customer records were copied from the coding service."),
  example("product passive later event", "Juniper 2.8 was compromised in the coding service."),
  example("product compound tense later event", "Juniper 2.8 has had a failure in the coding service."),
  example("launch property followed by independent action", "Juniper 2.8 improves coding, but Cedar Labs audited the service."),
  example("measurement followed by different actor", "Northstar measured the model, while Cedar Labs completed 42 reasoning trials."),
  example("measurement followed by unrelated action", "Northstar measured the model and stole customer records."),
  example("publisher quantified measurement", "Northstar ran 275 programming tasks on Juniper 2.8.", true),
  example("publisher passive quantified measurement", "275 programming tasks were executed by Northstar on Juniper 2.8.", true),
  example("publisher existing passive measurement", "Measurements of Juniper 2.8 were made by Northstar using 275 coding tasks.", true),
  example("benign safeguard state", "Benign security requests have fewer false positives. Watermark safeguards are included in the model release.", true),
  example("possessive safeguard description", "Our defensive safeguards now flag benign requests less often.", true),
  example("ancillary preview detail", "The announcement includes a service in private preview.", true),
  { name: "attributed incident is not a release result", mayMerge: false, inputs: [left,
    releaseEvidence("Juniper 2.8 coding isolation compared to its predecessor\nJuniper 2.8 is compromised (says Northstar). This release improves coding workloads vs its predecessor.", "right", "x-twitter"),
  ] },
];
