import { XObservationEvent, XObservationSendOffer } from "@social-monitor/contracts/generated/grpc/x_collector/v1/x_collector";
import { xAcquiredPostValid, xMetricValid, xPredecessorsMatch, xSupplementaryValid } from "../../domain/x-observation/x-observation-acquisition-contract";
import { acquisitionFixture, byteDigest, fixtureNow, offerFixture, outcomeFixture } from "../../domain/x-observation/x-observation.spec-support";
import { xCanonicalJson, xSemanticDigest } from "./x-observation-digest";
import { decodeXEvent, XOutcomeChunks } from "./x-observation-wire";

describe("additive observation prerequisites on current generated contracts", () => {
  it("preserves canonical digest ordering and rejects ambiguous numeric values", () => {
    expect(xCanonicalJson({ b: [1, "0"], a: true })).toBe('{"a":true,"b":[1,"0"]}');
    expect(xSemanticDigest({ a: 1, b: 2 })).toBe(xSemanticDigest({ b: 2, a: 1 }));
    for (const value of [NaN, Infinity, 0.5, { a: undefined }]) expect(() => xSemanticDigest(value)).toThrow();
    expect(xSemanticDigest({ a: "0" })).not.toBe(xSemanticDigest({ a: 0 }));
  });
  it("retains supplementary binding and exact predecessor bytes", () => {
    const { grant, current } = acquisitionFixture(xSemanticDigest);
    expect(xSupplementaryValid(grant, xSemanticDigest)).toBe(true);
    const matches = (evidence = current.predecessors) => xPredecessorsMatch(grant, evidence, current.ingestionPolicy, xSemanticDigest, byteDigest);
    expect(matches()).toBe(true);
    const first = current.predecessors[0]!;
    for (const patch of [{ predecessorArtifactBytes: [...first.predecessorArtifactBytes, 32] },
      { predecessorArtifact: { changed: true } }, { acceptance: "ACCEPTED" as const },
      { sourceBindingId: "other" }, { predecessorArtifactBytes: [256] }]) expect(matches([{ ...first, ...patch }])).toBe(false);
    expect(matches([first, first])).toBe(false);
    expect(xPredecessorsMatch(grant, current.predecessors, current.ingestionPolicy, xSemanticDigest)).toBe(false);
    if (grant.schemaVersion !== 2) throw new Error("fixture");
    expect(xSupplementaryValid({ ...grant, supplementary: { ...grant.supplementary,
      queries: [{ ...grant.supplementary.queries[0]!, pageLimit: 6 }] } }, xSemanticDigest)).toBe(false);
  });
  it("preserves public acquisition bounds and explicit metric presence", () => {
    const { post, query } = acquisitionFixture();
    expect(xAcquiredPostValid(post, query, fixtureNow)).toBe(true);
    for (const patch of [{ text: "😀".repeat(4097) }, { text: "\ud800" }, { primaryId: "0201" },
      { rawJson: {} }, { responseObservedAt: "2026-09-08T12:01:00.000Z" }]) expect(xAcquiredPostValid({ ...post, ...patch }, query, fixtureNow)).toBe(false);
    expect(xAcquiredPostValid({ ...post, text: "😀".repeat(4096) }, query, fixtureNow)).toBe(true);
    expect(xMetricValid({ state: "OBSERVED", valueDecimal: "0" })).toBe(true);
    for (const value of [{ state: "OBSERVED" }, { state: "MISSING", valueDecimal: "0" }, { state: "OBSERVED", valueDecimal: "01" }]) expect(xMetricValid(value)).toBe(false);
  });
  it("decodes a legacy offer with current generated bytes and rejects noncanonical envelopes", () => {
    const offer = offerFixture();
    const wire = XObservationSendOffer.fromJSON({ ...offer, stage: "X_OBSERVATION_STAGE_HOME" });
    const bytes = Buffer.from(XObservationEvent.encode({ sendOffer: wire }).finish());
    expect(decodeXEvent(bytes)).toEqual({ offer });
    for (const bad of [Buffer.alloc(0), Buffer.concat([bytes, bytes]), Buffer.concat([bytes, Buffer.from([0x78, 1])]), Buffer.alloc(256 * 1024 + 1), Buffer.from('{"schemaVersion":3}')]) {
      let error: unknown; try { decodeXEvent(bad); } catch (caught) { error = caught; }
      expect(error).toBeInstanceOf(Error); expect(error).not.toBeInstanceOf(TypeError);
      expect((error as Error).message).toMatch(/PROTOCOL_ERROR|premature EOF|invalid wire type|cant skip wire type [0-7]|illegal tag: field no \d+ wire type \d+|invalid varint|out of range/u);
    }
    expect(decodeXEvent(bytes)).toEqual({ offer });
    const future = XObservationSendOffer.fromJSON({ ...offer, stage: "FUTURE" });
    expect(() => decodeXEvent(Buffer.from(XObservationEvent.encode({ sendOffer: future }).finish()))).toThrow("PROTOCOL_ERROR");
  });
  it("preserves chunk order, header identity, acquisition version and aggregate bounds", () => {
    const base = outcomeFixture(), chunks = new XOutcomeChunks();
    expect(chunks.accept({ ...base, finalChunk: false })).toBeNull();
    expect(chunks.pending).toBe(true);
    expect(chunks.accept({ ...base, chunkIndex: 1 })).toEqual(base);
    expect(chunks.pending).toBe(false);
    expect(() => chunks.accept({ ...base, chunkIndex: 1 })).toThrow();
    chunks.accept({ ...base, finalChunk: false });
    expect(() => chunks.accept({ ...base, chunkIndex: 1, requestDigest: "b".repeat(64) })).toThrow();
    const { post } = acquisitionFixture();
    expect(() => new XOutcomeChunks().accept({ ...base, acquisition: { schemaVersion: 2, acquiredPosts: Array(101).fill(post) } })).toThrow();
    const mixed = new XOutcomeChunks();
    mixed.accept({ ...base, acquisition: { schemaVersion: 2, acquiredPosts: [] }, finalChunk: false });
    expect(() => mixed.accept({ ...base, chunkIndex: 1 })).toThrow();
    const bounded = new XOutcomeChunks();
    for (let chunkIndex = 0; chunkIndex < 20; chunkIndex++) expect(bounded.accept({ ...base, chunkIndex, finalChunk: false })).toBeNull();
    expect(() => bounded.accept({ ...base, chunkIndex: 20 })).toThrow();
  });
});
