import { tenantId, workspaceId } from "@social-monitor/shared-kernel";

import {
  emptyReaderSummaryReliabilityReport,
  ReaderSummaryArtifact,
} from "../../../domain";

export const readerSummaryArtifact = (
  readerSummaryId: string,
  modelVersion = "deterministic-local.v1",
): ReaderSummaryArtifact => ReaderSummaryArtifact.create({
  schemaVersion: "reader_summary.artifact.v1",
  readerSummaryId,
  tenantId: tenantId("tenant-reader-summary-prisma"),
  workspaceId: workspaceId("workspace-reader-summary-prisma"),
  scope: { type: "workspace" },
  period: {
    cadence: "daily",
    startedAt: new Date("2026-07-05T00:00:00.000Z"),
    endedAt: new Date("2026-07-06T00:00:00.000Z"),
    timezone: "UTC",
    periodKey: "daily:2026-07-05T00:00:00.000Z:2026-07-06T00:00:00.000Z:UTC",
  },
  sourceWindow: {
    windowId: "reader-window",
    startedAt: new Date("2026-07-05T08:00:00.000Z"),
    endedAt: new Date("2026-07-05T09:00:00.000Z"),
    selectedFeedItemIds: ["feed-1"],
    storyClusterIds: ["story-1"],
  },
  storyClusters: [{
    id: "story-1",
    storyKey: "url:example.test/story",
    representativeFeedItemId: "feed-1",
    duplicateFeedItemIds: [],
    interestIds: ["interest-ai"],
    providerKeys: ["rss"],
    score: 1.2,
    observedAtRange: {
      startedAt: new Date("2026-07-05T08:00:00.000Z"),
      endedAt: new Date("2026-07-05T09:00:00.000Z"),
    },
    whyImportant: ["Relevant source item."],
  }],
  contextArtifacts: [],
  headline: "Reader source signal",
  executiveSummary: "A reader source signal was selected.",
  content: {
    headline: "Reader source signal",
    oneLineTakeaway: "A reader source signal was selected.",
    bullets: ["A cited source item is relevant."],
    mainTopics: ["AI"],
    qualityState: {
      status: "ready",
      flags: [],
      warnings: [],
      isSingleSource: true,
    },
    interestSections: [],
    sourceMix: [{
      providerKey: "rss",
      itemCount: 1,
      citationCount: 1,
      storyClusterCount: 1,
      crossSourceClusterCount: 0,
      singleSourceOnly: true,
      interestIds: ["interest-ai"],
    }],
    topReads: [topRead()],
    selectedPosts: [topRead()],
    claimBoard: [],
    reliabilityReport: emptyReaderSummaryReliabilityReport(),
    trendDelta: {
      newSignals: ["1 RSS item selected"],
      growingSignals: [],
      repeatedSignals: [],
      fadingSignals: [],
    },
    risks: [],
    openQuestions: ["Is there confirming source evidence?"],
    nextActions: [],
  },
  topStories: [{
    storyClusterId: "story-1",
    title: "Reader source signal",
    summary: "A cited source item is relevant.",
    interestIds: ["interest-ai"],
    providerKeys: ["rss"],
    citationIds: ["citation-1"],
  }],
  interestHighlights: [],
  repeatedSignals: [],
  risksAndUnknowns: [],
  citationMap: [{
    citationId: "citation-1",
    feedItemId: "feed-1",
    sourceItemId: "source-1",
    providerKey: "rss",
    field: "bodyPreview",
    canonicalUrl: "https://example.test/story",
  }],
  qualityFlags: [],
  confidence: {
    level: "high",
    score: 0.9,
    rationale: "The source item is cited.",
  },
  lineage: {
    promptVersion: "reader-summary.prompt.test.v1",
    schemaVersion: "reader_summary.artifact.v1",
    modelVersion,
    providerVersion: "local",
    rulesVersion: "reader-summary.rules.v1",
    evalDatasetVersion: "reader-summary.eval.v1",
  },
  usage: { inputTokens: 100, outputTokens: 40, estimatedCostUsd: 0 },
});

export const topRead = () => ({
  storyClusterId: "story-1",
  cardKind: "curated_top_read" as const,
  title: "Reader source signal",
  providerKey: "rss",
  providerName: "RSS",
  primaryActionKind: "read_source" as const,
  reason: "It is relevant to the monitored topic.",
  matchedInterestIds: ["interest-ai"],
  matchedRules: ["ai"],
  signalScore: 1.2,
  confidence: {
    level: "medium" as const,
    score: 0.64,
    rationale: "The source item is cited.",
  },
  confirmedProviderKeys: ["rss"],
  providerMetrics: [],
  whyImportant: ["Relevant source item."],
  whyNow: "It appeared in the current summary window.",
  canonicalUrl: "https://example.test/story",
  citationIds: ["citation-1"],
  previewMedia: undefined,
});
